### ISSUE TITLE
 Requested environment is not available using selenoid binary on windows

### ISSUE THREAD

**Issue by AleksanderPopov** [aerokube/selenoid#114]
Hi guys! I try to launch selenoid via binary to run tests on windows machine without containers, using `selenoid v1.3.0x64`. I have following `browsers.json`:
`{
    "chrome": {
        "default": "58.0",
        "versions": {
            "58.0": {
                "image": ["C:\\drivers\\chrome\\chromedriver.exe", "--log-level=DEBUG"]
            }
        }
    }
}` 

Starting selenoid via `$ ./selenoid_windows_amd64.exe -conf browsers.json -disable-docker`.

And have test with following test class:
```
public class GoogleSearchTest {

    private SelenideElement search = $("#lst-ib");
    private ElementsCollection results = $$(".g .r");

    @BeforeClass
    public static void baseBeforeClass() throws MalformedURLException {
        DesiredCapabilities caps = DesiredCapabilities.chrome();
        WebDriverRunner.setWebDriver(new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), caps));
    }

    @Test
    public void searchAndFollowFirstResultTest() {

        open("http://google.com/ncr");
        search.setValue("Selenium automates browsers").pressEnter();
        results.filter(visible).shouldHaveSize(10)
                .first()
                .shouldHave(text("Selenium - Web Browser Automation"))
                .find("a")
                .click();
        assertUrl("http://www.seleniumhq.org/");
    }
    private void assertUrl(String url) {
        new WebDriverWait(getWebDriver(), 5).until(urlToBe(url));
    }
}
```

As a result of 'mvn test' i see in console:

```
Running GoogleSearchTest
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.389 sec <<< FAILURE!
GoogleSearchTest  Time elapsed: 1.388 sec  <<< ERROR!
org.openqa.selenium.WebDriverException: Requested environment is not available (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 196 milliseconds
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'DESKTOP-KFCUN4U', ip: '10.0.75.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
        at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
        at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:249)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:158)
        at GoogleSearchTest.baseBeforeClass(GoogleSearchTest.java:30)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)


Results :

Tests in error:
  GoogleSearchTest: Requested environment is not available (WARNING: The server did not provide any stacktrace information)(..)

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
```

And thats logs from selenoid hub:
```
$ ./selenoid_windows_amd64.exe -conf browsers.json -disable-docker
2017/06/08 09:40:40 Loading configuration files...
2017/06/08 09:40:40 Loaded configuration from [browsers.json]
2017/06/08 09:40:40 Using default containers log configuration because of: read error: open config/container-logs.json: The system cannot find the path specified.
2017/06/08 09:40:40 Timezone: Local
2017/06/08 09:40:40 Listening on :4444
2017/06/08 09:41:38 [NEW_REQUEST]
2017/06/08 09:41:38 [NEW_REQUEST_ACCEPTED]
2017/06/08 09:41:38 [0] [LOCATING_SERVICE] [chrome-]
2017/06/08 09:41:38 Using default version: 58.0
2017/06/08 09:41:38 [0] [USING_DRIVER] [chrome-58.0]
2017/06/08 09:41:38 [0] [ENVIRONMENT_NOT_AVAILABLE] [unknown] [chrome-58.0]
```

I tried the same settings with usual selenium grid jar's and it worked, but it does not with selenoid.
Can you please help me with this issue?

**Comment by vania-pooh** [comment]
@AleksanderPopov yes, that was fixed yesterday in #111. We'll release 1.3.1 during next days. Currently you can just downgrade to 1.2.1.

**Comment by AleksanderPopov** [comment]
@vania-pooh thank you for fast response, now it works fine!

**Comment by mom143** [comment]
Hi vania,

i am also faced the same issue in windows 7 environment,i used 1.3.9 version.
![selenoid_configissue](https://user-images.githubusercontent.com/29034252/32770076-4c1121bc-c944-11e7-8681-651d98ab41b2.PNG)

please suggest how resolve this issue.

**Comment by vania-pooh** [comment]
@mom143 this is a Windows security issue. According to [this] article the following should help in command line with admin rights:
```
> netsh winsock reset
```

**Comment by KathiresanRamkumar95** [comment]
Still Getting this issue even in selenoid:1.6.2. 

![image](https://user-images.githubusercontent.com/26536248/42813728-910eeb08-89df-11e8-8ff0-da5da1429e97.png)


Please help me to solve this!


@vania-pooh

**Comment by KathiresanRamkumar95** [comment]
Where I provide this details in this configuration?
@vania-pooh

**Comment by vania-pooh** [comment]
@KathiresanRamkumar95 ok, then just use capabilities shown in my previous comment.

**Comment by KathiresanRamkumar95** [comment]
How do I use that in my broswers.json. I mean which format. Can you provide a sample of them?
@vania-pooh

**Comment by vania-pooh** [comment]
@KathiresanRamkumar95 capabilities are specified in **test**, not in configuration file.

**Comment by Grosha** [comment]
@vania-pooh I have same error - verison 1.9.2
1.On windows VM runned command 
`C:\Backup\selenoid\selenoid_windows_amd64.exe -conf C:\Backup\selenoid\browsers.json -disable-docker -limit 2 > C:\Backup\selenoid\selenoid.log 2>&1`
File `browsers.json:`
`{
  "chrome": {
    "default": "77.0",
    "versions": {
      "77": {
        "image": ["C:\\Backup\\selenoid\\chromedriver.exe", "--log-level=DEBUG"]
      }
    }
  }
}`

2.On windows VM runned selenium hub
`java -jar selenium-server-standalone-3.9.1.jar -port 4445 -role hub`

3.On windows VM connected node to the hub
`java -jar selenium-server-standalone-3.9.1.jar -role node -nodeConfig C:\Backup\selenoid\selenium-node.json -hubHost localhost -hubPort 4445`

File `selenium-node.json`:
`{
	"capabilities": [{
		"browserName": "chrome",
		"version": "77.0",
		"maxInstances": 2,
		"seleniumProtocol": "WebDriver",
		"platform": "WINDOWS"
	}]
}`

4.On my (local) windows machine I run test with capabilities:
capabilities = {
                    "browserName": "chrome",
                    "version": "77.0",
                    "enableVNC": True,
                    "enableVideo": False,
                    "hostsEntries": domain_list
                }


Error:
`WARNING  root:driver_manager.py:94 Exeption on installing chrome driver process: Message: Requested environment is not available`

What is wrong?
