### ISSUE TITLE
Could not start a new session. Response code 500. Message: wait: http://172.18.0.8:4444 does not respond in 30s 

### ISSUE THREAD

**Issue by voha-ov** [aerokube/selenoid#1328]
Hello!

I faced with the issues
- "**2023-03-31 12:27:05org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: wait: http://172.18.0.8:4444/ does not respond in 30s**" 
- "**2023-03-31 02:53:33org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.** "

What can lead to those issues? 

During running tests status is shown next info:
{"state":{"total":10,"used":0,**"queued":11** **,"pending":10,**"browsers":{"MicrosoftEdge":{"15.0":{}},"chrome":{"latest":{}},"firefox":{"latest":{}},"safari":{"15.0":{}}},"videos":null},"origin":"http://selenoid:4444","browsers":{"MicrosoftEdge":0,"chrome":0,"firefox":0,"safari":0},"sessions":{},"version":"1.10.4[2021-10-10_08:53:47AM]","errors":[]}

I'm using 5 threads to run tests and whole run takes nearly 3 hours.

Selenoid version: 1.10.10

**Comment by pietrygamat** [comment]
I too started facing this exception 
```
Could` not start a new session. Response code 500. Message: wait: http://172.18.0.8:4444/ does not respond in 30s
```
when starting firefox:latest. 
Seemingly, the problem stareted when I updated to `selenoid/firefox:111.0`, because downgrading to `selenoid/firefox:110.0` or switching to chrome fixes the issue on my installation.

**Comment by soumyathampi** [comment]
Facing the same issue with firefox 111.0, downgrading to firefox 110.0 works fine.
error: "session not created"
message: "http://172.18.0.8:45241 does not respond in 30s"

**Comment by pdenaccusoft** [comment]
Facing same issue with Firefox 111.0, unable to start manual session through Selenoid UI.  Also tried new Firefox 111.0 image pushed 19 hours ago.

**Comment by vania-pooh** [comment]
This was fixed in Geckodriver 0.33.0. We have rebuilt respective Firefox 111.0 image - try to repull.

**Comment by voha-ov** [comment]
@vania-pooh what about chrome?

**Comment by vania-pooh** [comment]
@voha-ov invalid `-container-network` flag value.

**Comment by pdenaccusoft** [comment]
@vania-pooh I re-pulled the Firefox 111.0 image and am still seeing issue.  The last rebuild looks to be from 2 days ago, was that when it was addressed?

**Comment by voha-ov** [comment]
> @voha-ov invalid `-container-network` flag value.

Could you be more specific?)

**Comment by vania-pooh** [comment]
@pdenaccusoft will check one more time.

**Comment by vania-pooh** [comment]
Issue with Firefox 111.0 images was fixed in https://github.com/aerokube/selenoid/issues/1329.
